version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  backend:
    image: luppiters/kittygram_backend
    env_file: .env
    command: ["gunicorn", "--bind", "0.0.0.0:9000", "--timeout", "120", "kittygram_backend.wsgi"]
    volumes:
      - static_volume:/backend_static
      - media_volume:/media

  frontend:
    image: luppiters/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static_volume/
    volumes:
      - static_volume:/static_volume

  nginx:
    image: luppiters/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
